hollymovies/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.urls import path, include

from accounts.views import user_logout, SignUpView
from api.views import Movies, MovieDetail
from hollymovies import settings
from viewer.views import *

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', home, name='home'),
    path('movies/', MoviesListView.as_view(), name='movies'),
    path('movie/<int:pk>/', MovieDetailView.as_view(), name='movie'),
    #path('movie/create/', MovieFormView.as_view(), name='movie_create'),
    path('movie/create/', MovieCreateView.as_view(), name='movie_create'),
    path('movie/update/<int:pk>/', MovieUpdateView.as_view(), name='movie_update'),
    path('movie/delete/<int:pk>/', MovieDeleteView.as_view(), name='movie_delete'),
    path('movie/filter/', movie_filter, name='movie_filter'),
    path('creators/', CreatorsListView.as_view(), name='creators'),
    path('creator/<int:pk>/', CreatorDetailView.as_view(), name='creator'),
    path('creator/create/', CreatorCreateView.as_view(), name='creator_create'),
    path('creator/update/<int:pk>/', CreatorUpdateView.as_view(), name='creator_update'),
    path('creator/delete/<int:pk>/', CreatorDeleteView.as_view(), name='creator_delete'),
    path('actors/', ActorsView.as_view(), name='actors'),
    path('countries/', CountriesListView.as_view(), name='countries'),
    path('country/<int:pk>/', CountryDetailView.as_view(), name='country'),
    path('country/create/', CountryCreateView.as_view(), name='country_create'),
    path('country/update/<int:pk>/', CountryUpdateView.as_view(), name='country_update'),
    path('country/delete/<int:pk>/', CountryDeleteView.as_view(), name='country_delete'),
    path('genres/', GenresListView.as_view(), name='genres'),
    path('genre/<int:pk>/', GenreDetailView.as_view(), name='genre'),
    path('genre/create/', GenreFormView.as_view(), name='genre_create'),
    path('genre/update/<int:pk>/', GenreUpdateView.as_view(), name='genre_update'),
    path('genre/delete/<int:pk>/', GenreDeleteView.as_view(), name='genre_delete'),
    path('images/', ImageListView.as_view(), name='images'),
    path('image/<int:pk>/', ImageDetailView.as_view(), name='image'),
    path('image/create/', ImageCreateView.as_view(), name='image_create'),
    path('image/update/<int:pk>/', ImageUpdateView.as_view(), name='image_update'),
    path('image/delete/<int:pk>/', ImageDeleteView.as_view(), name='image_delete'),
    path('review/delete/<int:pk>/', ReviewDeleteView.as_view(), name='review_delete'),

    path('accounts/login/', LoginView.as_view(template_name='form.html'), name='login'),
    path('accounts/logout/', user_logout, name='logout'),
    path('accounts/password_change/',
         PasswordChangeView.as_view(template_name='form.html'),
         name='password_change'),
    # ostatní defaultní cesty
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', SignUpView.as_view(), name='signup'),

    path('nameday/', name_day, name='nameday'),
    path('search/', search, name='search'),

    path('api/movies/', Movies.as_view(), name='api_movies'),
    path('api/movie/<int:pk>/', MovieDetail.as_view(), name='api_movie'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

viewer/models.py
from django.db.models import Model, CharField, DateField, ForeignKey, SET_NULL, \
    TextField, DateTimeField, ManyToManyField, IntegerField, ImageField, CASCADE

from accounts.models import Profile


class Genre(Model):
    name = CharField(max_length=32, null=False, blank=False, unique=True)

    class Meta:
        ordering = ['name']

    def __repr__(self):
        return f"Genre(name={self.name})"

    def __str__(self):
        return self.name


class Country(Model):
    name = CharField(max_length=32, null=False, blank=False, unique=True)

    class Meta:
        ordering = ['name']
        verbose_name_plural = 'Countries'

    def __repr__(self):
        return f"Country(name={self.name})"

    def __str__(self):
        return self.name


class Creator(Model):
    name = CharField(max_length=32, null=True, blank=True)
    surname = CharField(max_length=32, null=True, blank=True)
    artistic_name = CharField(max_length=32, null=True, blank=True)
    date_of_birth = DateField(null=True, blank=True)
    date_of_death = DateField(null=True, blank=True)
    country = ForeignKey(Country, null=True, blank=True, on_delete=SET_NULL, related_name='creators')
    biography = TextField(null=True, blank=True)
    created = DateTimeField(auto_now_add=True)
    updated = DateTimeField(auto_now=True)

    class Meta:
        ordering = ['surname', 'name', 'artistic_name', 'date_of_birth']

    def __repr__(self):
        return f"Creator(name={self.name}, surname={self.surname}, artictic_name={self.artistic_name})"

    def __str__(self):
        if self.date_of_birth:
            return f"{self.name} {self.surname} ({self.date_of_birth.year})"
        return f"{self.name} {self.surname}"

    def full_name(self):
        full_name_ = ''
        if self.name:
            full_name_ += self.name + ' '
        if self.artistic_name:
            full_name_ += f'"{self.artistic_name}" '
        if self.surname:
            full_name_ += self.surname
        return full_name_


class Movie(Model):
    title_orig = CharField(max_length=64, null=False, blank=False, unique=False)
    title_cz = CharField(max_length=64, null=True, blank=True)
    genres = ManyToManyField(Genre, blank=True, related_name='movies')
    directors = ManyToManyField(Creator, blank=True, related_name='directing')
    actors = ManyToManyField(Creator, blank=True, related_name='acting')
    composers = ManyToManyField(Creator, blank=True, related_name='composing')
    length = IntegerField(null=True, blank=True)
    description = TextField(null=True, blank=True)
    year = IntegerField(null=True, blank=True)
    countries = ManyToManyField(Country, blank=True, related_name='movies')
    created = DateTimeField(auto_now_add=True)
    updated = DateTimeField(auto_now=True)

    class Meta:
        ordering = ['title_orig', 'year']

    def __repr__(self):
        if self.year:
            return f"Movie(title_orig={self.title_orig}, year={self.year})"
        return f"Movie(title_orig={self.title_orig})"

    def __str__(self):
        if self.year:
            return f"{self.title_orig} ({self.year})"
        return f"{self.title_orig}"

    def length_format(self):
        # převod délky filmu z minut na formát h:mm
        # 142 min -> 2:22
        # 122 min -> 2:02
        if self.length:
            hours = self.length // 60
            minutes = self.length % 60
            return f"{hours}:{minutes:02}"
            #return f"{hours}h {minutes}min"
        return None


class Image(Model):
    image = ImageField(upload_to='images/', default=None, null=False, blank=False)
    movie = ForeignKey(Movie, on_delete=SET_NULL, null=True, blank=True, related_name='images')
    creators = ManyToManyField(Creator, blank=True, related_name='images')
    description = TextField(null=True, blank=True)

    def __repr__(self):
        return f"Image(image={self.image})"

    def __str__(self):
        return f"Image: {self.image}"


class Review(Model):
    movie = ForeignKey(Movie, on_delete=CASCADE, null=False, blank=False, related_name='reviews')
    reviewer = ForeignKey(Profile, on_delete=SET_NULL, null=True, blank=False, related_name='reviews')
    rating = IntegerField(null=True, blank=True)
    comment = TextField(null=True, blank=True)
    created = DateTimeField(auto_now_add=True)
    updated = DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-updated']

    def __repr__(self):
        return (f"Review(movie={self.movie}, "
                f"reviewer={self.reviewer}, "
                f"rating={self.rating}, "
                f"comment={self.comment[:20]})")

    def __str__(self):
        return f"{self.reviewer}: {self.movie} ({self.rating})"

viewer/forms.py
import re
from datetime import date

from django.core.exceptions import ValidationError
from django.forms import Form, CharField, ModelChoiceField, IntegerField, \
    Textarea, ModelForm, TextInput, DateField, NumberInput

from viewer.models import Genre, Creator, Country, Movie, Image, Review


class GenreForm(Form):
    name = CharField(label='Název žánru', max_length=32, required=True)

    def clean_name(self):
        initial = self.cleaned_data['name']
        return initial.capitalize()


class GenreModelForm(ModelForm):
    class Meta:
        model = Genre
        fields = '__all__'

        labels = {
            'name': 'Název žánru'
        }

    def clean_name(self):
        initial = self.cleaned_data['name']
        return initial.capitalize()


"""
class MovieForm(Form):
    title_orig = CharField(label='Originální název', max_length=64, required=True)
    title_cz = CharField(label='Český název', max_length=64, required=False)
    genres = ModelChoiceField(label='Žánry', queryset=Genre.objects, required=False)
    directors = ModelChoiceField(label='Režie', queryset=Creator.objects, required=False)
    actors = ModelChoiceField(label='Herci', queryset=Creator.objects, required=False)
    composers = ModelChoiceField(label='Hudba', queryset=Creator.objects, required=False)
    length = IntegerField(label='Délka', required=False)
    description = CharField(label='Popis', widget=Textarea, required=False)
    year = IntegerField(label='Rok', required=False)
    countries = ModelChoiceField(label='Země', queryset=Country.objects, required=False)
"""


class MovieModelForm(ModelForm):
    class Meta:
        model = Movie
        fields = '__all__'

        labels = {
            'title_orig': 'Originální název',
            'title_cz': 'Český název',
            'genres': 'Žánry',
            'directors': 'Režie',
            'actors': 'Herci',
            'composers': 'Hudba',
            'length': 'Délka',
            'description': 'Popis',
            'year': 'Rok',
            'countries': 'Země'
        }

        help_texts = {
            'length': 'Délka filmu v minutách.',
            'description': 'Popis filmu, stručný obsah nebo jiné detaily.'
        }

        error_messages = {
            'title_orig': {
                'required': 'Tento údaj je povinný.'
            }
        }

    title_orig = CharField(max_length=64,
                           required=True,
                           widget=TextInput(attrs={'class': 'bg-info'}),
                           label='Originální název')

    def clean_title_orig(self):
        initial = self.cleaned_data['title_orig']
        return initial.capitalize()

    def clean_title_cz(self):
        initial = self.cleaned_data['title_cz']
        if initial:
            return initial.capitalize()
        return initial

    def clean_length(self):
        initial = self.cleaned_data['length']
        if initial is not None and int(initial) <= 0:
            raise ValidationError('Délka filmu musí být kladné číslo.')
        return initial


class CountryModelForm(ModelForm):
    class Meta:
        model = Country
        fields = '__all__'

        labels = {
            'name': 'Název země'
        }

    def clean_name(self):
        initial = self.cleaned_data['name']
        return initial.capitalize()


class CreatorModelForm(ModelForm):
    class Meta:
        model = Creator
        #fields = ['name', 'surname', 'artistic_name']
        #exclude = ['biography']
        fields = '__all__'

        labels = {
            'name': 'Jméno',
            'surname': 'Příjmení',
            'artistic_name': 'Umělecké jméno',
            'date_of_birth': 'Datum narození',
            'date_of_death': 'Datum úmrtí',
            'country': 'Země',
            'biography': 'Biografie'
        }

    date_of_birth = DateField(required=False,
                              widget=NumberInput(attrs={'type': 'date'}),
                              label='Datum narození')
    date_of_death = DateField(required=False,
                              widget=NumberInput(attrs={'type': 'date'}),
                              label='Datum úmrtí')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

    def clean_name(self):
        initial = self.cleaned_data['name']
        if initial:
            return initial.capitalize()
        return initial

    def clean_surname(self):
        initial = self.cleaned_data['surname']
        if initial:
            return initial.capitalize()
        return initial

    def clean_artistic_name(self):
        initial = self.cleaned_data['artistic_name']
        if initial:
            return initial.capitalize()
        return initial

    def clean_date_of_birth(self):
        initial = self.cleaned_data['date_of_birth']
        if initial and initial > date.today():
            raise ValidationError('Datum narození nesmí být v budoucnosti.')
        return initial

    def clean_date_of_death(self):
        initial = self.cleaned_data['date_of_death']
        if initial and initial > date.today():
            raise ValidationError('Datum úmrtí nesmí být v budoucnosti.')
        return initial

    def clean_biography(self):
        initial = self.cleaned_data['biography']
        sentences = re.sub(f'\s*\.\s*', '.', initial).split('.')
        return '. '.join(sentence.capitalize() for sentence in sentences)

    def clean(self):
        cleaned_data = super().clean()
        error_message = ''
        initial_surname = cleaned_data.get('surname')
        initial_artistic_name = cleaned_data.get('artistic_name')
        if not initial_surname and not initial_artistic_name:
            error_message += 'Je nutné zadat příjmení nebo umělecké jméno (nebo obojí).'
            #raise ValidationError('Je nutné zadat příjmení nebo umělecké jméno (nebo obojí).')

        initial_date_of_birth = cleaned_data.get('date_of_birth')
        initial_date_of_death = cleaned_data.get('date_of_death')
        if initial_date_of_birth and initial_date_of_death and initial_date_of_death <= initial_date_of_birth:
            error_message += ' Datum úmrtí nesmí být dřív, než datum narození.'
            #raise ValidationError('Datum úmrtí nesmí být dřív, než datum narození.')

        if error_message:
            raise ValidationError(error_message)

        return cleaned_data


class ImageModelForm(ModelForm):
    class Meta:
        model = Image
        fields = '__all__'


class ReviewModelForm(ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'comment']

        labels = {
            'rating': 'Hodnocení',
            'comment': 'Komentář'
        }

    rating = IntegerField(min_value=1,
                          max_value=10,
                          required=False,
                          label='Hodnocení')

    def clean(self):
        cleaned_data = super().clean()
        rating = cleaned_data.get('rating')
        comment = cleaned_data.get('comment')
        if not rating and not comment:
            raise ValidationError("Je nutné zadat hodnocení nebo komentář (nebo oboje).")

viewer/templates/actors.html
{% extends 'base.html' %}

{% block title %}
    Seznam herců
{% endblock %}

{% block content %}
    <h1>Seznam herců</h1>
    <ul>
        {% for actor in actors %}
            <li>
                {{ actor }}
            </li>
        {% empty %}
            v databázi není žádný herec.
        {% endfor %}
    </ul>
{% endblock %}

viewer/templates/countries.html
{% extends 'base.html' %}

{% block title %}
    Seznam zemí
{% endblock %}

{% block content %}
    <h1>Seznam zemí</h1>
    <a href="{% url 'country_create' %}" class="btn btn-primary">Přidat zemi</a>
    <ul>
        {% for country in countries %}
            <li><a href="{% url 'country' country.id %}">{{ country }}</a>
                <a href="{% url 'country_update' country.id %}">✏️</a>
                <a href="{% url 'country_delete' country.id %}">❌</a>
                <br>
                Počet filmů: {{ country.movies.count }} <br>
                <ul>
                    {% for movie in country.movies.all %}
                        <li><a href="{% url 'movie' movie.id %}">{{ movie }}</a>
                        </li>
                    {% endfor %}
                </ul>
                Počet tvůrců: {{ country.creators.count }}
                <ul>
                    {% for creator in country.creators.all %}
                        <li>
                            <a href="{% url 'creator' creator.id %}">{{ creator }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

viewer/templates/creator.html
{% extends 'base.html' %}

{% block title %}
    {{ creator.full_name }}
{% endblock %}

{% block content %}
    <h1 class="display-4">{{ creator.full_name }}</h1>

    <div class="creator-images">
        {% for image in creator.images.all %}
            <span class="creator-image">
                <a href="{% url 'image' image.id %}">
                    <img src="{{ image.image.url }}"
                         alt="{{ image.description }}"
                        width="150px">
                </a>
            </span>
        {% endfor %}
    </div>

    <div class="row">
        <div class="col-md-6">
            <p><strong>Země:</strong>
                <span class="badge badge-secondary">
                    {% if creator.country %}
                        <a href="{% url 'country' creator.country.id %}" class="text-white">{{ creator.country }}</a>
                    {% endif %}
                </span>
            </p>
            <p>
                <strong>Datum narození:</strong>
                {{ creator.date_of_birth|date:"j. n. Y" }}
            </p>
            {% if creator.date_of_death|date:"j. n. Y" %}
                <p>
                    <strong>Datum úmrtí:</strong>
                    {{ creator.date_of_death }}
                </p>
            {% endif %}
        </div>
        <div class="col-md-6">
            {% if creator.acting.exists %}
                <p>
                    <strong>Herec ve filmech:</strong>
                    {% for movie in creator.acting.all %}
                        <a href="{% url 'movie' movie.id %}">{{ movie }}</a>{% if not forloop.last %},{% endif %}
                    {% comment %}{% empty %}
                        Nehrál v žádném filmu. {% endcomment %}
                    {% endfor %}
                </p>
            {% endif %}
            {% if creator.directing.exists %}
                <p>
                    <strong>Režisér filmů:</strong>
                    {% for movie in creator.directing.all %}
                        <a href="{% url 'movie' movie.id %}">{{ movie }}</a>{% if not forloop.last %},{% endif %}
                    {% comment %}{% empty %}
                        Nerežíroval žádný film. {% endcomment %}
                    {% endfor %}
                </p>
            {% endif %}
            {% if creator.composing.exists %}
                <p>
                    <strong>Skladatel:</strong>
                    {% for movie in creator.composing.all %}
                        <a href="{% url 'movie' movie.id %}">{{ movie }}</a>{% if not forloop.last %},{% endif %}
                    {% comment %}{% empty %}
                        Nesložil hudbu k žádnému filmu. {% endcomment %}
                    {% endfor %}
                </p>
            {% endif %}
        </div>
    </div>
    <p><strong>Biografie:</strong></p>
    <p class="text-justify">{{ creator.biography }}</p>

    <p class="mt-3">
        <small class="text-muted">
            Přidáno do databáze: {{ creator.created|date:"j. n. Y G:i:s" }}
        </small>
    </p>
    <p>
        <small class="text-muted">
            Poslední úprava: {{ creator.updated|date:"j. n. Y G:i:s" }}
        </small>
    </p>
    {% if perms.viewer.change_creator %}
        <a href="{% url 'creator_update' creator.id %}" class="btn btn-primary">Aktualizovat</a>
    {% endif %}
    {% if perms.viewer.delete_creator %}
        <a href="{% url 'creator_delete' creator.id %}" class="btn btn-danger">Smazat</a>
    {% endif %}
{% endblock %}

viewer/templates/creators.html
{% extends 'base.html' %}

{% block title %}
    Seznam tvůrců
{% endblock %}

{% block content %}
    {% if perms.viewer.add_creator %}
        <a href="{% url 'creator_create' %}" class="btn btn-primary">Přidat tvůrce</a>
    {% endif %}
    {% comment %}
    <h1>Seznam tvůrců</h1>
    <ul>
        {% for creator in creators %}
            <li>
                {{ creator }}
            </li>
        {% empty %}
            V databázi není žádný tvůrce.
        {% endfor %}
    </ul>
    {% endcomment %}

    <h1>Seznam herců</h1>
    <ul>
        {% for creator in creators %}
            {% if creator.acting.all %}
                <li>
                    <a href="{% url 'creator' creator.id %}">{{ creator }}</a>
                    {% if perms.viewer.change_creator %}
                        <a href="{% url 'creator_update' creator.id %}">✏️</a>
                    {% endif %}
                    {% if perms.viewer.delete_creator %}
                        <a href="{% url 'creator_delete' creator.id %}">❌</a>
                    {% endif %}
                </li>
            {% endif %}
        {% empty %}
            V databázi není žádný herec.
        {% endfor %}
    </ul>

    <h1>Seznam režisérů</h1>
    <ul>
        {% for creator in creators %}
            {% if creator.directing.all %}
                <li>
                    <a href="{% url 'creator' creator.id %}">{{ creator }}</a>
                    {% if perms.viewer.change_creator %}
                        <a href="{% url 'creator_update' creator.id %}">✏️</a>
                    {% endif %}
                    {% if perms.viewer.delete_creator %}
                        <a href="{% url 'creator_delete' creator.id %}">❌</a>
                    {% endif %}
                </li>
            {% endif %}
        {% empty %}
            V databázi není žádný režisér.
        {% endfor %}
    </ul>

    <h1>Seznam skladatelů</h1>
    <ul>
        {% for creator in creators %}
            {% if creator.composing.all %}
                <li>
                    <a href="{% url 'creator' creator.id %}">{{ creator }}</a>
                    {% if perms.viewer.change_creator %}
                        <a href="{% url 'creator_update' creator.id %}">✏️</a>
                    {% endif %}
                    {% if perms.viewer.delete_creator %}
                        <a href="{% url 'creator_delete' creator.id %}">❌</a>
                    {% endif %}
                </li>
            {% endif %}
        {% empty %}
            V databázi není žádný skladatel.
        {% endfor %}
    </ul>
{% endblock %}

viewer/templates/movie.html
{% extends 'base.html' %}

{% block title %}
    {{ movie }}
{% endblock %}

{% block content %}
    <h1 class="display-4">{{ movie.title_orig|upper }}</h1>
    <p class="lead">{{ movie.title_cz }}</p>

    <div class="movie-images">
        {% for image in movie.images.all %}
            <span class="movie-image">
                <a href="{% url 'image' image.id %}">
                    <img src="{{ image.image.url }}"
                         alt="{{ image.description }}"
                         width="150px">
                </a>
            </span>
        {% endfor %}
    </div>

    <hr class="my-4">
    <div class="row">
        <div class="col-md-6">
            <p><strong>Žánry:</strong>
                {% for genre in movie.genres.all %}
                    <span class="badge badge-secondary">
                        <a href="{% url 'genre' genre.id %}" class="text-white">{{ genre }}</a>
                    </span>
                {% empty %}
                    bez žánru
                {% endfor %}
            </p>
            <p><strong>Země:</strong>
                {% for country in movie.countries.all %}
                    <span class="badge badge-secondary">
                        <a href="{% url 'country' country.id %}" class="text-white">{{ country }}</a>
                    </span>
                {% empty %}
                    bez země
                {% endfor %}
            </p>
            <p><strong>Délka:</strong>
                {% comment %}{{ movie.length }} minut {% endcomment %}
                {{ movie.length_format }}
            </p>
            <p><strong>Rok:</strong>
                {{ movie.year }}
            </p>
        </div>
        <div class="col-md-6">
            <p><strong>Režie:</strong>
                {% for director in movie.directors.all %}
                    <a href="{% url 'creator' director.id %}">{{ director.full_name }}</a>{% if not forloop.last %},{% endif %}
                {% empty %}
                    bez režiséra
                {% endfor %}
            </p>
            <p><strong>Hrají:</strong>
                {% for actor in movie.actors.all %}
                    <a href="{% url 'creator' actor.id %}">{{ actor.full_name }}</a>{% if not forloop.last %},{% endif %}
                {% empty %}
                    bez herce
                {% endfor %}
            </p>
            <p><strong>Hudba:</strong>
                {% for composer in movie.composers.all %}
                    <a href="{% url 'creator' composer.id %}">{{ composer.full_name }}</a>{% if not forloop.last %},{% endif %}
                {% empty %}
                    bez hudebníka
                {% endfor %}
            </p>
        </div>
    </div>
    <p><strong>Popis:</strong></p>
    <p class="text-justify">{{ movie.description }}</p>

    <p class="mt-3">
        <small class="text-muted">
            Přidáno do databáze: {{ movie.created|date:"j. n. Y G:i:s" }}
        </small>
    </p>
    <p>
        <small class="text-muted">
            Poslední úprava: {{ movie.updated|date:"j. n. Y G:i:s" }}
        </small>
    </p>

    {% if perms.viewer.change_movie %}
        <a href="{% url 'movie_update' movie.id %}" class="btn btn-primary">Aktualizovat</a>
    {% endif %}
    {% if perms.viewer.delete_movie %}
        <a href="{% url 'movie_delete' movie.id %}" class="btn btn-danger">Smazat</a>
    {% endif %}

    {% if request.user.is_authenticated %}
        <form action="" method="post">
            {% csrf_token %}
            <table>{{ review_form.as_table }}</table>
            <button type="submit">Odeslat</button>
        </form>
    {% endif %}

    <hr>
    {% for review in movie.reviews.all %}
        <div class="bg-light rounded mt-2 p-2 position-relative">
            <span>Uživatel: {{ review.reviewer }}</span>
            <span class="font-italic">{{ review.created|date:'d. m. Y H:i' }}</span>
            {% if review.created != review.updated %}
                <span class="font-italic">(upraveno: {{ review.updated|date:'d. m. Y H:i' }})</span>
            {% endif %}
            {% if request.user == review.reviewer.user %}
                <a href="{% url 'review_delete' review.id %}">Smazat</a>
            {% endif %}
            <div>
                Hodnocení: {{ review.rating }}
            </div>
            <div>
                Komentář: {{ review.comment }}
            </div>
        </div>
    {% empty %}
        Zatím nikdo nehodnotil tento film.
    {% endfor %}

{% endblock %}

viewer/templates/movies.html
{% extends 'base.html' %}

{% block title %}
    Seznam filmů
{% endblock %}

{% block content %}

    <div class="filter-form">
        <form method="post" action="/movie/filter/" class="form-row align-items-center">
            {% csrf_token %}

            <div class="col-auto col-sm-1">
                <input type="text" id="filter-genre" name="filter-genre"
                       class="form-control form-control-sm" placeholder="Žánr">
            </div>

            <div class="col-auto col-sm-1">
                <input type="text" id="filter-country" name="filter-country"
                       class="form-control form-control-sm" placeholder="Země">
            </div>

            <div class="col-auto col-sm-1">
                <input type="text" id="filter-actor" name="filter-actor"
                       class="form-control form-control-sm" placeholder="Herec">
            </div>

            <div class="col-auto col-sm-1">
                <input type="text" id="filter-year-from" name="filter-year-from"
                       class="form-control form-control-sm" placeholder="Rok od">
            </div>

            <div class="col-auto col-sm-1">
                <input type="text" id="filter-year-to" name="filter-year-to"
                       class="form-control form-control-sm" placeholder="do">
            </div>

            <div class="col-auto">
                <input type="submit" id="id_submit" value="Filtr"
                       class="btn btn-primary btn-sm">
            </div>
        </form>
    </div>

    <h1>Seznam filmů</h1>
    {% if perms.viewer.add_movie %}
        <a href="{% url 'movie_create' %}" class="btn btn-primary">Přidat film</a>
    {% endif %}
    <ul>
        {% for movie in movies %}
            <li>
                <a href="{% url 'movie' movie.id %}">{{ movie }}</a>
                {% if perms.viewer.change_movie %}
                    <a href="{% url 'movie_update' movie.id %}">✏️</a>
                {% endif %}
                {% if perms.viewer.delete_movie %}
                    <a href="{% url 'movie_delete' movie.id %}">❌</a>
                {% endif %}
            </li>
        {% empty %}
            V databázi není žádný film.
        {% endfor %}
    </ul>
{% endblock %}

viewer/templates/nameday.html
{% extends 'base.html' %}

{% block title %}
    Svátek: {{ name }}
{% endblock %}

{% block content %}
    Dnes má svátek: {{ name }}
{% endblock %}